version: '3.3'
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=lightl
      - POSTGRES_USER=lightl
      - POSTGRES_PASSWORD=lightl

  redis:
    image: redis:latest


  django:
    image: jamesbuxter/django:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASS=django
      - DEBUG=True
      - MY_SECRET=secret_key
      - REDIS_HOST=redis
    command: |
      python manage.py runserver 0.0.0.0:8000

  worker:
    image: jamesbuxter/django:latest
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASS=django
      - REDIS_HOST=redis
    command: |
      python manage.py rqworker