# Generated by Django 4.1.7 on 2023-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/image_item_default.png",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
