# Generated by Django 4.1.7 on 2023-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(related_name='products', to='reviews.review'),
        ),
    ]
